---
# Setup installation repositories
# Standart repository for Debian / Ubuntu (https://www.rabbitmq.com/install-debian.html)
- name: import repository key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    update_cache: yes
    state: present

